### ISSUE TITLE
Class 'ExtensionsValley\Ranger\RangerServiceProvider' not found

### ISSUE THREAD

**Issue by hm43** [LaFlux/Laflux#2]
http://demo.laflux.com/admin/dashboard

FatalErrorException in ProviderRepository.php line 146:
Class 'ExtensionsValley\Ranger\RangerServiceProvider' not found

**Comment by Jobinjose01** [comment]
Thanks for reporting issue , we are looking into the problem
Last update breaks something.

**Comment by hm43** [comment]
Good luck.
